version: "3.9"

services:
  db:
    image: postgres:14
    container_name: tala_trivia_db
    environment:
      POSTGRES_USER: tala
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: talatrivia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: tala_trivia_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+psycopg2://tala:1234@db:5432/talatrivia
    ports:
      - "8000:8000"

volumes:
  postgres_data:
